name: TheiaHelper
version: '${version}'
main: me.jerriidesu.theiahelper.TheiaHelper
api-version: 1.16
commands:
  togglesponge:
    aliases:
      - tos
  togglepickup:
    aliases:
      - top
  sitdown:
    aliases:
      - sit
  flyspeed:
    aliases:
      - fs